### ISSUE TITLE
Compatibility with verbatimModuleSyntax

### ISSUE THREAD

**Issue by aetos382** [ShaneGH/magic-odata#82]
The compile option `verbatimModuleSyntax` was added in TypeScript 5.0.
If this option is `true`, imports of types that are not used in the code or only used as type names will fail without the `type` modifier.

At the top of the generated OData Client code, many types are imported, including those that are not used.
To avoid compile errors, could you please make sure that unused types are not imported, or add the `type` modifier appropriately?

**Comment by sconnon-repay** [comment]
@aetos382 thanks for that, I will look into it

**Comment by ShaneGH** [comment]
Fixed in https://github.com/ShaneGH/magic-odata/releases/tag/v1.1.1
https://www.npmjs.com/package/magic-odata-client/v/1.1.1

There are still 1 or 2 dependencies that are not matched with a `type`, but are necessary if you have at least 1 endpoint.
Let me know if you still have any issues
